In [1]:
print("Hello World")

Hello World


In [2]:
list1 =["apple","Mangoes","fruits"]
print(list1)

['apple', 'Mangoes', 'fruits']


In [3]:
# add the element
list1.append("banana")
print(list1)

['apple', 'Mangoes', 'fruits', 'banana']


# **Numerical Python**
  1.Allows several mathematical operations  
  2.Faster operations

In [5]:
import numpy as np

List vs Numpy - Time taken

In [6]:
from time import process_time

Time taken by list

In [12]:
py_list = [i for i in range(10000)]
start_time1 = process_time()
py_list = [i+5 for i in py_list]
end_time1 = process_time()
print(end_time1-start_time1)

0.0015595860000008344


In [13]:
n_array = np.array([i for i in range(10000)])
start_time2 = process_time()
n_array+=5
end_time2 = process_time()
print(end_time2-start_time2)

0.0013242870000009788


Numpy Arrays

In [15]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [16]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [17]:
# Creating a one dimensional array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [18]:
a.shape

(5,)

In [19]:
d2 = np.array([(1,2,3,4),(5,6,7,8)])
print(d2)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
d2.shape

(2, 4)

In [22]:
 a2 = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
 print(a2)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [23]:
#created a numpy array of zeroes
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
x.shape

(4, 4)

In [25]:
x.dtype

dtype('float64')

In [26]:
#create a numpy array of ones
x2 = np.ones((3,3))
print(x2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [28]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# Create a numpy array with random values
a2 = np.random.random((3,4))
print(a2)

[[0.739171   0.39266789 0.05304883 0.79552325]
 [0.52775695 0.63997245 0.9896884  0.00222017]
 [0.7889433  0.46180531 0.58082911 0.68000107]]


In [31]:
# Random integers values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[92 80 40 84 53]
 [17 92 25 67 21]
 [49 48 92 96 78]]


In [36]:
# array of evenly spaced values ....> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [37]:
#array of evenly spaced values ...> specifying the step
d2 = np.arange(10,30,5)
print(d2)

[10 15 20 25]


In [38]:
#Convert a list to a numpy array
list2 = [10,20,20,30,40]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 30 40]


numpy.ndarray

Analyzing the Numpy array

In [39]:
c = np.random.randint(10,60,(5,5))
print(c)

[[48 21 31 14 39]
 [48 26 15 34 40]
 [36 23 51 25 26]
 [22 56 12 33 18]
 [14 28 38 57 52]]


In [40]:
# Array Dimensions
print(c.shape)

(5, 5)


In [42]:
#Number of dimensions in array
print(c.ndim)

2


In [43]:
#Number of elements in array
print(c.size)

25


In [44]:
# Checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [45]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #Concate or join in two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [46]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [47]:
print(a)
print(b)

[[7 0 5]
 [1 2 4]
 [5 9 6]]
[[11 19 13]
 [15 12 18]
 [18 11 19]]


In [48]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 19 18]
 [16 14 22]
 [23 20 25]]
[[ -4 -19  -8]
 [-14 -10 -14]
 [-13  -2 -13]]
[[ 77   0  65]
 [ 15  24  72]
 [ 90  99 114]]
[[0.63636364 0.         0.38461538]
 [0.06666667 0.16666667 0.22222222]
 [0.27777778 0.81818182 0.31578947]]


In [49]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [50]:
print(a)
print(b)

[[9 8 9]
 [8 7 9]
 [7 8 0]]
[[13 18 11]
 [15 13 14]
 [11 17 19]]


In [51]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 26 20]
 [23 20 23]
 [18 25 19]]
[[ -4 -10  -2]
 [ -7  -6  -5]
 [ -4  -9 -19]]
[[117 144  99]
 [120  91 126]
 [ 77 136   0]]
[[0.69230769 0.44444444 0.81818182]
 [0.53333333 0.53846154 0.64285714]
 [0.63636364 0.47058824 0.        ]]


**Array Manipulation**

In [52]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 6 1]
 [7 0 0]]
(2, 3)


In [55]:
#transpose of array
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 7]
 [6 0]
 [1 0]]
(3, 2)


In [56]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 1 4]
 [4 5 1]]
(2, 3)


In [57]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 4]
 [1 5]
 [4 1]]
(3, 2)


In [58]:
# Reshaping the array
a =np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[2 3 6]
 [9 3 4]]
(2, 3)


In [59]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 3]
 [6 9]
 [3 4]]
(3, 2)
